openapi: 3.0.3
info:
  title: API.Rasp.Yandex.Net
  description: API Яндекс.Расписаний
  version: 3.0.0
servers:
  - url: https://api.rasp.yandex.net
tags:
  - name: Список ближайших станций
    description: Список ближайших станций

paths:
  /v3.0/nearest_stations/:
    get:
      tags: [getNearestStations]
      summary: Список ближайших станций
      operationId: getNearestStations
      parameters:
        - name: apikey
          in: query
          description: API key
          required: true
          schema: { type: string }
        - name: lat
          in: query
          description: Широта согласно WGS84
          required: true
          schema: { type: number }
        - name: lng
          in: query
          description: Долгота согласно WGS84
          required: true
          schema: { type: number }
        - name: distance
          in: query
          description: Радиус охвата в километрах
          required: true
          schema: { type: integer }
        - name: lang
          in: query
          description: Язык возвращаемой информации (например, ru_RU)
          schema: { type: string }
        - name: format
          in: query
          description: Формат ответа (json или xml)
          schema: { type: string }
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stations'

  /v3.0/search/:
    get:
      tags: [getScheduleBetweenStations]
      summary: Расписание рейсов между станциями
      operationId: getScheduleBetweenStations
      parameters:
        - name: apikey
          in: query
          required: true
          schema: { type: string }
        - name: from
          in: query
          required: true
          schema: { type: string }
        - name: to
          in: query
          required: true
          schema: { type: string }
        - name: date
          in: query
          schema: { type: string }
        - name: transport_types
          in: query
          schema: { type: string }
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Segments'

  /v3.0/schedule/:
    get:
      tags: [getStationSchedule]
      summary: Список рейсов по станции
      operationId: getStationSchedule
      parameters:
        - name: apikey
          in: query
          required: true
          schema: { type: string }
        - name: station
          in: query
          required: true
          schema: { type: string }
        - name: date
          in: query
          schema: { type: string }
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScheduleResponse'

  /v3.0/thread/:
    get:
      tags: [getRouteStations]
      summary: Список станций следования по нитке
      operationId: getRouteStations
      parameters:
        - name: apikey
          in: query
          required: true
          schema: { type: string }
        - name: uid
          in: query
          required: true
          schema: { type: string }
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThreadStationsResponse'

  /v3.0/nearest_settlement/:
    get:
      tags: [getNearestCity]
      summary: Ближайший город
      operationId: getNearestCity
      parameters:
        - name: apikey
          in: query
          required: true
          schema: { type: string }
        - name: lat
          in: query
          required: true
          schema: { type: number }
        - name: lng
          in: query
          required: true
          schema: { type: number }
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NearestCityResponse'

  /v3.0/carrier/:
    get:
      tags: [getCarrierInfo]
      summary: Информация о перевозчике
      operationId: getCarrierInfo
      parameters:
        - name: apikey
          in: query
          required: true
          schema: { type: string }
        - name: code
          in: query
          description: Код перевозчика
          required: true
          schema: { type: string }
        - name: system
          in: query
          description: Система кодирования (yandex, iata, sirena, express, esr)
          required: false
          schema: { type: string }
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CarrierResponse'

  /v3.0/stations_list/:
    get:
      tags: [getAllStations]
      summary: Список всех станций
      operationId: getAllStations
      parameters:
        - name: apikey
          in: query
          required: true
          schema: { type: string }
      responses:
        "200":
          description: Успешный ответ
          content:
            text/html; charset=utf-8:
              schema:
                $ref: '#/components/schemas/AllStationsResponse'

  /v3.0/copyright/:
    get:
      tags: [copyright]
      summary: Копирайт
      operationId: getCopyright
      parameters:
        - name: apikey
          in: query
          required: true
          schema: { type: string }
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CopyrightResponse'

components:
  schemas:
    Pagination:
      type: object
      properties:
        total: { type: integer }
        limit: { type: integer }
        offset: { type: integer }

    Station:
      type: object
      properties:
        code: { type: string }
        title: { type: string }
        transport_type: { type: string }
        lat: { type: number }
        lng: { type: number }

    Stations:
      type: object
      properties:
        pagination:
          $ref: '#/components/schemas/Pagination'
        stations:
          type: array
          items:
            $ref: '#/components/schemas/Station'

    Segments:
      type: object
      properties:
        pagination:
          $ref: '#/components/schemas/Pagination'
        segments:
          type: array
          items:
            type: object
            properties:
              from: { $ref: '#/components/schemas/Station' }
              to: { $ref: '#/components/schemas/Station' }
              departure: { type: string }
              arrival: { type: string }

    ScheduleResponse:
      type: object
      properties:
        date: { type: string }
        station: { $ref: '#/components/schemas/Station' }
        schedule:
          type: array
          items:
            type: object
            properties:
              thread:
                type: object
                properties:
                  title: { type: string }
                  transport_type: { type: string }

    ThreadStationsResponse:
      type: object
      properties:
        uid: { type: string }
        title: { type: string }
        stops:
          type: array
          items:
            $ref: '#/components/schemas/Station'

    NearestCityResponse:
      type: object
      properties:
        distance: { type: number }
        title: { type: string }
        code: { type: string }

    CarrierResponse:
      type: object
      properties:
        carrier:
          $ref: '#/components/schemas/Carrier'
          nullable: true
          description: Единичный перевозчик (для кодов Яндекса)
        carriers:
          type: array
          items:
            $ref: '#/components/schemas/Carrier'
          nullable: true
          description: Массив перевозчиков (для IATA и т.п.)

    Carrier:
      type: object
      properties:
        code:
          type: integer    # ← вот это главное исправление: число, не строка
          description: Код перевозчика
        title:
          type: string
          description: Название перевозчика
        url:
          type: string
        contacts:
          type: string
        phone:
          type: string
        address:
          type: string
        logo:
          type: string
        email:
          type: string

    AllStationsResponse:
      type: object
      properties:
        countries:
          type: array
          items:
            type: object
            properties:
              title: { type: string }
              regions:
                type: array
                items:
                  type: object
                  properties:
                    title: { type: string }

    CopyrightResponse:
      type: object
      properties:
        copyright:
          type: object
          properties:
            text: { type: string }
            url: { type: string }
